// Real roster data extracted from westernbeats.com
export type Artist = {
  name: string
  image: string
  genre: string
  location: string
  experience: string
  followers: string
  description: string
  achievements: string[]
  hits: string[]
  instagram?: string
  youtube?: string
  spotify?: string
}

export const ARTISTS: Artist[] = [
  {
    name: 'Sapna Choudhary',
    image: '/artists/sapnachoudhary-DkPyzJGL.jpg',
    genre: 'Haryanvi / Folk Pop',
    location: 'Haryana, India',
    experience: '12+ Years',
    followers: '4.5M+',
    description: 'Cultural icon who has revolutionised Haryanvi music with her powerful voice and contemporary approach.',
    achievements: ['Cultural Icon of Haryana', 'YouTube Sensation', 'Best Folk Artist Award'],
    hits: ['Chatak Matak', 'Jale 2', 'Fouji Fojan 2'],
    instagram: 'https://www.instagram.com/itssapnachoudhary',
    youtube: 'https://www.youtube.com/@_Sapna_Choudhary_official',
    spotify: 'https://open.spotify.com/artist/5WYVZzKOZMUn4pNY9gy2BM',
  },
  {
    name: 'Sumit Parta',
    image: '/artists/sumitparta.jpg',
    genre: 'Haryanvi / Folk',
    location: 'Haryana, India',
    experience: '6+ Years',
    followers: '800K+',
    description: 'Rising Haryanvi folk voice whose soulful compositions resonate deeply with regional audiences.',
    achievements: ['Regional Hit Maker', 'Folk Rising Star', 'YouTube Featured'],
    hits: ['Folk Anthems', 'Regional Hits', 'Live Concerts'],
    instagram: 'https://www.instagram.com/sumitparta',
  },
  {
    name: 'Renuka Panwar',
    image: '/artists/renukapanwar-AsuFBi3-.jpg',
    genre: 'Haryanvi / Pop',
    location: 'Haryana, India',
    experience: '8+ Years',
    followers: '2.1M+',
    description: 'Authentic Haryanvi pop voice bringing contemporary style to traditional folk music.',
    achievements: ['Pop Artist of the Year', 'Regional Music Award', 'Multi-Platinum'],
    hits: ['52 Gaj Ka Daman', 'Kabootar', 'Yanta'],
    instagram: 'https://www.instagram.com/renukapanwar',
    youtube: 'https://www.youtube.com/@RenukaPanwarSinger',
    spotify: 'https://open.spotify.com/artist/2wDTo0nO2ZKJN7VUeGmuyg',
  },
  {
    name: 'Harsh Sandhu',
    image: '/artists/harshsandhu-CfMNV-ao.jpeg',
    genre: 'Punjabi / Hip-Hop',
    location: 'Punjab, India',
    experience: '6+ Years',
    followers: '3.2M+',
    description: 'Contemporary Punjabi singer-songwriter blending modern sounds with traditional Punjabi music.',
    achievements: ['Contemporary Artist Award', 'Youth Icon Award', 'Diamond Records'],
    hits: ['Bandook', 'Gentleman 2', 'Chulla Nondh'],
    instagram: 'https://www.instagram.com/harshsandhuofficial',
    youtube: 'https://youtube.com/@harshsandhuoffical',
    spotify: 'https://open.spotify.com/artist/6ojAHTLwaSTS3DhFeajzft',
  },
  {
    name: 'RJ Spider',
    image: '/artists/rjspider-Hof4RhHx.jpg',
    genre: 'Hip-Hop / Electronic',
    location: 'Mumbai, India',
    experience: '7+ Years',
    followers: '1.9M+',
    description: 'Dynamic hip-hop artist and radio jockey bringing urban culture to the forefront of Indian music.',
    achievements: ['Hip Hop Artist of the Year', 'Radio Excellence Award', 'Urban Music Pioneer'],
    hits: ['Shyano Ji', 'W.T.F', 'Tota Naffa'],
    instagram: 'https://www.instagram.com/r_j_spider',
    youtube: 'https://youtube.com/@rjspider',
    spotify: 'https://open.spotify.com/artist/3O7hlIVRhJerMH3QuYDAkZ',
  },
  {
    name: 'Khotu Kharkhada',
    image: '/artists/khotukharkhada-Bt2vw7sN.jpg',
    genre: 'Haryanvi / Traditional Folk',
    location: 'Haryana, India',
    experience: '15+ Years',
    followers: '750K+',
    description: 'Traditional Haryanvi folk artist preserving and promoting the authentic culture of Haryana.',
    achievements: ['Cultural Heritage Award', 'Folk Music Excellence', 'Regional Artist of the Year'],
    hits: ['Shyano Ji', 'Bombay Paar', 'Neeli Neeli Aankh'],
    instagram: 'https://www.instagram.com/khotu_kharkhada',
    spotify: 'https://open.spotify.com/artist/06fmZLGLQlgnlzyGqniuqZ',
  },
  {
    name: 'Kalakaar',
    image: '/artists/kalakaar-xIyvru5G.jpg',
    genre: 'Fusion / World',
    location: 'Delhi, India',
    experience: '9+ Years',
    followers: '1.1M+',
    description: 'Versatile fusion artist masterfully blending traditional Indian music with contemporary global sounds.',
    achievements: ['Fusion Music Award', 'Cultural Innovation Award', 'Global Music Excellence'],
    hits: ['Bombay Paar', 'O Gori', 'Bhola Bhola Rakhe'],
    instagram: 'https://www.instagram.com/kalakaar_._._',
    youtube: 'https://youtube.com/@kalakaarofficial-1m',
    spotify: 'https://open.spotify.com/artist/4zuIuj8j9aOWqSyxcUilnA',
  },
  {
    name: 'Nidhi Sharma',
    image: '/artists/nidhisharma-CGmPjw--.jpeg',
    genre: 'Bollywood / Pop',
    location: 'India',
    experience: '5+ Years',
    followers: '1.2M+',
    description: 'Versatile Bollywood and pop vocalist with a modern melodic sensibility.',
    achievements: ['Playback Artist', 'Spotify Featured', 'Regional Hits'],
    hits: ['Featured Singles', 'Live Sessions', 'Collaborations'],
    instagram: 'https://www.instagram.com/nidhisharmaofficiall',
    youtube: 'https://youtube.com/@nidhisharmaofficial',
    spotify: 'https://open.spotify.com/artist/1oUC0FZ7PmdPnT6iax2fsC',
  },
  {
    name: 'Vikram Sarkar',
    image: '/artists/vikramsarkar.jpg',
    genre: 'Punjabi / Pop',
    location: 'Punjab, India',
    experience: '5+ Years',
    followers: '600K+',
    description: 'Punjabi pop sensation crafting chart-topping tracks that blend tradition with modern beats.',
    achievements: ['Punjabi Pop Star', 'Youth Favourite', 'Trending Artist'],
    hits: ['Hit Singles', 'Trending Tracks', 'Live Performances'],
    instagram: 'https://www.instagram.com/vikramsarkar',
  },
  {
    name: 'R Maan',
    image: '/artists/rmaan-CLokcRnr.jpeg',
    genre: 'Punjabi / Folk',
    location: 'Punjab, India',
    experience: '8+ Years',
    followers: '900K+',
    description: 'Soulful Punjabi voice known for heartfelt compositions that connect culture and emotion.',
    achievements: ['Folk Icon', 'Platinum Artist', 'Cultural Ambassador'],
    hits: ['Popular Singles', 'Folk Classics', 'Collaborations'],
    instagram: 'https://www.instagram.com/rmaan',
  },
  {
    name: 'Ajay Hooda',
    image: '/artists/ajayhooda.jpg',
    genre: 'Haryanvi / Folk',
    location: 'Haryana, India',
    experience: '10+ Years',
    followers: '2.8M+',
    description: 'Legendary Haryanvi folk artist whose powerful voice and authentic style have made him an icon of the genre.',
    achievements: ['Haryanvi Legend', 'Multi-Platinum Artist', 'Folk Heritage Award'],
    hits: ['Dil Main Tu', 'Current Laga Re', 'Bado Badi'],
    instagram: 'https://www.instagram.com/ajayhooda',
    youtube: 'https://youtube.com/@ajayhooda',
  },
]

export const PARTNERS = [
  { name: 'Warner Music India',   logo: '/partners/warnermusicindia-3pJs86tg.png' },
  { name: 'JetSynthesys',         logo: '/partners/jetsynthesys-E9Hauft9.png' },
  { name: 'Global Music Junction',logo: '/partners/globalmusicjunction-C0M0W2-z.png' },
  { name: 'GIG',                  logo: '/partners/gig-logo.png' },   // ← upload gig-logo.png to /public/partners/
]
