import type { Metadata } from 'next'
import TermsPage from './TermsPage'

export const metadata: Metadata = {
  title: 'Terms & Conditions | WB Digital: Western Beats Private Limited',
  description:
    'Full Terms & Conditions for WB Digital by Western Beats Private Limited. Understand the 75% artist / 25% WB royalty split, 100% IP ownership, free distribution to 150+ platforms, go-live timelines, payout policies, and your rights as an artist.',
  keywords: [
    'WB Digital terms and conditions',
    'Western Beats terms of service',
    'music distribution terms India',
    'WB Digital royalty split',
    'music distribution agreement India',
    'WB Digital 75% royalties',
    'artist royalty terms India',
    'free music distribution terms',
    'Warner Music India distribution agreement',
    'music distribution legal India',
  ],
  alternates: { canonical: 'https://westernbeats.com/terms' },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-snippet': -1 },
  },
  openGraph: {
    title: 'Terms & Conditions | WB Digital: Western Beats',
    description:
      'Read the full WB Digital terms: 75% royalties to you, 100% IP ownership, free distribution to 150+ platforms in 48-72 hours. Transparent, fair, India-first.',
    url: 'https://westernbeats.com/terms',
    siteName: 'WB Digital: Western Beats',
    type: 'website',
    locale: 'en_IN',
  },
  twitter: {
    card: 'summary',
    title: 'Terms & Conditions | WB Digital',
    description:
      '75% royalties to you, 100% IP ownership, free distribution to 150+ platforms. Read our full T&C.',
    site: '@wb_digital_',
  },
}

const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'WebPage',
      '@id': 'https://westernbeats.com/terms#webpage',
      url: 'https://westernbeats.com/terms',
      name: 'Terms & Conditions | WB Digital: Western Beats Private Limited',
      description:
        'Full Terms & Conditions for WB Digital by Western Beats Private Limited, covering royalty splits, ownership, distribution, payouts, and artist rights.',
      isPartOf: { '@id': 'https://westernbeats.com/#website' },
      about: { '@id': 'https://westernbeats.com/#organization' },
      breadcrumb: {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://westernbeats.com' },
          { '@type': 'ListItem', position: 2, name: 'Terms & Conditions', item: 'https://westernbeats.com/terms' },
        ],
      },
    },
    {
      '@type': 'FAQPage',
      mainEntity: [
        {
          '@type': 'Question',
          name: 'What is the royalty split on WB Digital?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'WB Digital operates on a 75% artist / 25% WB split on net royalties. You receive 75% of all streaming and download income generated by your music across 150+ platforms. WB retains 25% as a service fee — there are no upfront charges, so we only earn when you earn.',
          },
        },
        {
          '@type': 'Question',
          name: 'Does "100% ownership" mean I keep all royalties?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: '"100% ownership" refers to your intellectual property rights: you retain full copyright, master recording rights, and creative control over your music at all times. It does not refer to revenue share. Revenue is split 75% to the artist and 25% to WB Digital as per the distribution agreement.',
          },
        },
        {
          '@type': 'Question',
          name: 'Is WB Digital really free to use?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Yes. There are zero upfront fees, no annual subscription, and no per-release charges. WB Digital earns solely through the 25% royalty share on income your music generates. If your music earns nothing, WB Digital earns nothing.',
          },
        },
        {
          '@type': 'Question',
          name: 'When does WB Digital pay artists?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'WB Digital pays royalties monthly, directly to your registered bank account. A minimum payout threshold of ₹500 applies. Any balance below ₹500 rolls over to the following month.',
          },
        },
        {
          '@type': 'Question',
          name: 'How long does it take for music to go live after uploading?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Music distributed through WB Digital goes live on platforms within 48-72 hours of submission. Tracks uploaded on Friday typically go live by Monday. Go-live time may vary slightly depending on individual platform processing times.',
          },
        },
        {
          '@type': 'Question',
          name: 'Can I remove my music from WB Digital?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Yes. You may request removal of your music at any time by contacting WB Digital. Upon termination or removal, WB will initiate a takedown from all 150+ platforms within the standard platform processing timeframes. Any accrued royalties owed to you will be paid out as per the regular payout schedule.',
          },
        },
      ],
    },
  ],
}

export default function Terms() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <TermsPage />
    </>
  )
}
