import type { Metadata } from 'next'
import TermsPage from './TermsPage'

export const metadata: Metadata = {
  title: 'Terms & Conditions | Content Licensing Agreement — Western Beats Private Limited',
  description:
    'Full Terms & Conditions and Content Licensing Agreement for Western Beats Private Limited. Covers the 70% artist / 30% WB royalty split, 100% IP ownership, 2-year term, 12-month lock-in, distribution to 150+ platforms, payout policy, arbitration in Mumbai, and all artist rights.',
  keywords: [
    'Western Beats terms and conditions',
    'Western Beats content licensing agreement',
    'music distribution terms India',
    'Western Beats royalty split 70 percent',
    'music distribution agreement India',
    'Western Beats 70% royalties artists',
    'artist royalty terms India',
    'free music distribution agreement India',
    'Warner Music India Partner distribution terms',
    'music distribution legal India',
    'artist lock-in period music distribution',
    'Western Beats artist obligations',
    'content licensing agreement music India',
    'Western Beats Private Limited PAN AACCW9613Q',
  ],
  alternates: { canonical: 'https://westernbeats.com/terms' },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-snippet': -1 },
  },
  openGraph: {
    title: 'Terms & Conditions | Western Beats Private Limited',
    description:
      'Read the full Western Beats Content Licensing Agreement: 70% royalties to you, 100% IP ownership, 2-year term with 12-month lock-in, distribution to 150+ platforms in 72 hours. Transparent, legally precise, India-first.',
    url: 'https://westernbeats.com/terms',
    siteName: 'Western Beats',
    type: 'website',
    locale: 'en_IN',
  },
  twitter: {
    card: 'summary',
    title: 'Terms & Conditions | Western Beats',
    description:
      '70% royalties to you, 100% IP ownership, 150+ platforms. Full Content Licensing Agreement for Western Beats Private Limited.',
    site: '@wb_digital_',
  },
}

const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'WebPage',
      '@id': 'https://westernbeats.com/terms#webpage',
      url: 'https://westernbeats.com/terms',
      name: 'Terms & Conditions | Content Licensing Agreement — Western Beats Private Limited',
      description:
        'Full Terms & Conditions and Content Licensing Agreement for Western Beats Private Limited, covering royalty splits, IP ownership, term & lock-in, distribution services, artist obligations, indemnification, arbitration, and all artist rights.',
      isPartOf: { '@id': 'https://westernbeats.com/#website' },
      about: { '@id': 'https://westernbeats.com/#organization' },
      breadcrumb: {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://westernbeats.com' },
          { '@type': 'ListItem', position: 2, name: 'Terms & Conditions', item: 'https://westernbeats.com/terms' },
        ],
      },
    },
    {
      '@type': 'FAQPage',
      mainEntity: [
        {
          '@type': 'Question',
          name: 'What is the royalty split on Western Beats?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Western Beats operates on a 70% artist / 30% WB split on net royalties. You receive 70% of all net streaming and download income generated by your music across 150+ platforms. WB retains 30% as a Distribution Fee — covering infrastructure, platform relationships, marketing, ISRC/UPC, and operations. There are no upfront charges.',
          },
        },
        {
          '@type': 'Question',
          name: 'Does "100% ownership" mean I keep all royalties?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: '"100% ownership" refers to your intellectual property rights — you retain full copyright, master recording rights, and creative control over your music at all times. It does not refer to revenue share. Revenue is split 70% to the artist and 30% to Western Beats as per the Content Licensing Agreement.',
          },
        },
        {
          '@type': 'Question',
          name: 'Is there a lock-in period with Western Beats?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Yes. The first 12 months from the Agreement\'s Effective Date is a mandatory lock-in period. During this period, you cannot terminate the Agreement for any reason, except in the event of an Event of Default by WB (i.e., WB fails to pay your Revenue Share for more than 3 continuous months).',
          },
        },
        {
          '@type': 'Question',
          name: 'What is the term of the agreement?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'The Initial Term is 2 years from the Effective Date. After the Initial Term, the Agreement renews for additional periods as mutually agreed by both Parties.',
          },
        },
        {
          '@type': 'Question',
          name: 'When does Western Beats pay artists?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Western Beats pays within 30 days of receiving a valid invoice from you. Reports are provided after 2 months for YouTube and quarterly for OTT and other platforms. After receiving the report, you have 15 days to raise any queries, after which you must submit an invoice. YouTube invoices are raised monthly; OTT invoices quarterly.',
          },
        },
        {
          '@type': 'Question',
          name: 'Can I distribute my music through other platforms while signed with WB?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'No. Western Beats holds exclusive distribution rights to your content during the Agreement Term. You cannot distribute the licensed content through any other distributor, label, or platform independently during this period. Doing so constitutes a material breach of the Agreement.',
          },
        },
        {
          '@type': 'Question',
          name: 'Can I remove my music from Western Beats?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'After the 12-month lock-in period, you may request termination by contacting WB. Upon termination, WB has a 30-day cool-off period to remove Content from all Distribution Methods. All accrued royalties owed to you are paid out per the regular schedule.',
          },
        },
        {
          '@type': 'Question',
          name: 'Where are disputes resolved?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Any disputes that cannot be resolved amicably are referred to binding arbitration under the Arbitration and Conciliation Act, 1996. The place of arbitration is Mumbai, India. The language of arbitration is English. The Agreement is governed by the laws of India and subject to the exclusive jurisdiction of Mumbai courts.',
          },
        },
      ],
    },
  ],
}

export default function Terms() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <TermsPage />
    </>
  )
}
